service: gcf-executor

provider:
  name: google
  runtime: nodejs
  project: project-name
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:

  gcf-executor-256:
    handler: gcf_executor_256
    memorySize: 256
    timeout: 540s
    events:
    - http: path

  gcf-executor-128:
    handler: gcf_executor_128
    memorySize: 128
    timeout: 540s
    events:
    - http: path

  gcf-executor-512:
    handler: gcf_executor_512
    memorySize: 512
    timeout: 540s
    events:
    - http: path

  gcf-executor-1024:
    handler: gcf_executor_1024
    memorySize: 1024
    timeout: 540s
    events:
    - http: path

  gcf-executor-2048:
    handler: gcf_executor_2048
    memorySize: 2048
    timeout: 540s
    events:
    - http: path
